"use client";

import Link from "next/link";
import { Check, Clock3, Send } from "lucide-react";
import { useApp } from "@/components/providers/app-provider";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { formatHours } from "@/lib/utils";

export default function DailyPlanPage() {
  const { dailyPlan, tasks, updateTask } = useApp();
  if (!dailyPlan) return <div className="mx-auto max-w-3xl"><Card><CardContent className="py-20 text-center"><Clock3 className="mx-auto h-8 w-8 text-slate-300" /><h1 className="mt-4 text-2xl font-semibold">No daily plan has been generated</h1><p className="mx-auto mt-2 max-w-lg text-sm leading-6 text-slate-500">Create a project and approve tasks first. The configured morning workflow will build a real dependency-aware plan and send it to Telegram.</p><Link href="/projects"><Button className="mt-5">Open projects</Button></Link></CardContent></Card></div>;
  const completed = dailyPlan.items.filter((item) => tasks.find((task) => task.id === item.taskId)?.status === "completed" || item.completed).length;
  const percentage = dailyPlan.items.length ? Math.round(completed / dailyPlan.items.length * 100) : 0;
  return <div className="space-y-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold text-sky-700">{dailyPlan.planDate}</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Daily plan</h1><p className="mt-2 text-slate-500">{dailyPlan.summary}</p></div><span className="rounded-full bg-emerald-50 px-3 py-1.5 text-sm font-semibold text-emerald-700">{formatHours(dailyPlan.totalPlannedHours)} planned</span></div><div className="grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><Card><CardHeader><div><h2 className="text-xl font-semibold">Today’s focus blocks</h2><p className="mt-1 text-sm text-slate-500">{completed} of {dailyPlan.items.length} completed</p></div><span className="text-2xl font-semibold">{percentage}%</span></CardHeader><CardContent><Progress value={percentage} /><div className="mt-5 space-y-3">{dailyPlan.items.map((item, index) => { const task = tasks.find((entry) => entry.id === item.taskId); const done = task?.status === "completed" || item.completed; return <div key={item.id} className={`flex items-center gap-3 rounded-2xl border p-4 ${done ? "border-emerald-200 bg-emerald-50" : "border-slate-200"}`}><button disabled={!task} onClick={() => task && void updateTask(task.id, done ? Math.min(task.progressPercent, 75) : 100, done ? "in_progress" : "completed")} className={`grid h-10 w-10 shrink-0 place-items-center rounded-xl border ${done ? "border-emerald-500 bg-emerald-500 text-white" : "border-slate-200 bg-white text-slate-300"}`} aria-label={`${done ? "Reopen" : "Complete"} ${item.title}`}><Check className="h-4 w-4" /></button><div className="min-w-0 flex-1"><div className="flex gap-2"><span className="text-xs font-semibold text-slate-400">{String(index + 1).padStart(2, "0")}</span><p className={`font-semibold ${done ? "text-emerald-900 line-through" : ""}`}>{item.title}</p></div><p className="mt-1 text-sm text-slate-500">{item.projectTitle} · {item.reason}</p></div><span className="inline-flex items-center gap-1.5 rounded-lg bg-white px-2.5 py-1 text-sm font-semibold shadow-sm"><Clock3 className="h-3.5 w-3.5" />{formatHours(item.plannedMinutes / 60)}</span></div>; })}</div></CardContent></Card><Card className="border-sky-900 bg-[#122033] text-white"><CardHeader><div><p className="text-xs text-sky-300">Telegram</p><h2 className="mt-1 font-semibold">Morning plan preview</h2></div><Send className="h-4 w-4 text-sky-300" /></CardHeader><CardContent className="text-sm leading-6 text-slate-200"><ol className="list-inside list-decimal space-y-1">{dailyPlan.items.map((item) => <li key={item.id}>{item.title} — {formatHours(item.plannedMinutes / 60)}</li>)}</ol><p className="mt-4"><strong>Total:</strong> {formatHours(dailyPlan.totalPlannedHours)}</p><p className="mt-3 text-sky-200">{dailyPlan.riskSummary}</p></CardContent></Card></div></div>;
}
