"use client";
import { format, parseISO } from "date-fns";
import { CalendarDays, Flag, Milestone } from "lucide-react";
import { useApp } from "@/components/providers/app-provider";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader } from "@/components/ui/card";

export default function CalendarPage() { const { projects, tasks } = useApp(); const events = [...tasks.filter((task) => !["completed","cancelled"].includes(task.status)).map((task) => ({ date: task.dueDate, title: task.title, subtitle: projects.find((project) => project.id === task.projectId)?.title ?? "Project", kind: task.status === "blocked" ? "blocked" : "task" })), ...projects.filter((project) => project.status === "active").map((project) => ({ date: project.finalDeadline, title: project.title, subtitle: "Final deadline", kind: "deadline" }))].sort((a,b) => a.date.localeCompare(b.date)); return <div className="space-y-6"><div><p className="text-sm font-semibold text-sky-700">Schedule</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Timeline</h1><p className="mt-2 text-slate-500">Project deadlines, internal targets, milestones, and task due dates.</p></div><div className="grid gap-6 xl:grid-cols-[.65fr_1.35fr]"><Card><CardHeader><h2 className="text-lg font-semibold">July 2026</h2><CalendarDays className="h-5 w-5 text-slate-400" /></CardHeader><CardContent><div className="grid grid-cols-7 gap-1 text-center text-xs"><>{["M","T","W","T","F","S","S"].map((day,index) => <span key={`${day}-${index}`} className="py-2 font-semibold text-slate-400">{day}</span>)}</>{Array.from({length:35},(_,index) => { const day=index-1; const hasEvent=events.some((event)=> Number(event.date.slice(-2))===day); return <div key={index} className={`relative grid aspect-square place-items-center rounded-lg ${day===19 ? "bg-slate-950 font-semibold text-white" : day>0&&day<=31 ? "hover:bg-slate-100" : "text-slate-200"}`}>{day>0&&day<=31?day:""}{hasEvent&&day!==19&&<span className="absolute bottom-1 h-1 w-1 rounded-full bg-sky-500" />}</div>; })}</div></CardContent></Card><Card><CardHeader><div><p className="text-xs font-semibold uppercase tracking-wider text-slate-400">Upcoming</p><h2 className="mt-1 text-xl font-semibold">What lands next</h2></div><Badge tone="info">{events.length} dates</Badge></CardHeader><CardContent><div className="space-y-1">{events.map((event,index) => <div key={`${event.date}-${event.title}`} className="grid grid-cols-[64px_auto_1fr] gap-3 py-3"><div className="text-center"><p className="text-lg font-semibold">{format(parseISO(event.date),"d")}</p><p className="text-[10px] font-semibold uppercase text-slate-400">{format(parseISO(event.date),"MMM")}</p></div><div className={`mt-1 grid h-9 w-9 place-items-center rounded-xl ${event.kind === "deadline" ? "bg-rose-50 text-rose-600" : event.kind === "blocked" ? "bg-amber-50 text-amber-600" : "bg-sky-50 text-sky-600"}`}>{event.kind === "deadline" ? <Flag className="h-4 w-4" /> : <Milestone className="h-4 w-4" />}</div><div className={index < events.length-1 ? "border-b border-slate-100 pb-3" : ""}><p className="font-medium">{event.title}</p><p className="mt-1 text-sm text-slate-500">{event.subtitle}</p></div></div>)}</div></CardContent></Card></div></div>; }

