"use client";
import Link from "next/link";
import { format, parseISO } from "date-fns";
import { Archive, ArrowUpRight, CalendarDays, MoreHorizontal, Pin, RotateCcw } from "lucide-react";
import type { Project } from "@/lib/types";
import { initials } from "@/lib/utils";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";

const tones = { on_track: "success", at_risk: "warning", delayed: "danger", blocked: "danger", completed: "success" } as const;
const colors: Record<Project["projectType"], string> = { subject: "bg-indigo-100 text-indigo-700", assignment: "bg-sky-100 text-sky-700", examination: "bg-rose-100 text-rose-700", competition: "bg-violet-100 text-violet-700", hackathon: "bg-fuchsia-100 text-fuchsia-700", final_year_project: "bg-emerald-100 text-emerald-700", internship: "bg-orange-100 text-orange-700", event: "bg-amber-100 text-amber-700", personal: "bg-cyan-100 text-cyan-700", other: "bg-slate-100 text-slate-700" };
export function ProjectCard({ project, onArchive, onActivate, archived = false }: { project: Project; onArchive(): void; onActivate?(): void; archived?: boolean }) {
  return <article className="group relative rounded-2xl border border-slate-200 bg-white p-5 transition hover:-translate-y-0.5 hover:border-slate-300 hover:shadow-lg hover:shadow-slate-200/50"><div className="flex items-start gap-3"><div className={`grid h-11 w-11 shrink-0 place-items-center rounded-2xl text-sm font-bold ${colors[project.projectType]}`}>{initials(project.title)}</div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><h2 className="truncate font-semibold">{project.title}</h2>{project.isActiveContext ? <Pin className="h-3.5 w-3.5 fill-sky-500 text-sky-500" /> : null}</div><p className="mt-1 text-xs capitalize text-slate-400">{project.projectType.replaceAll("_", " ")} · {project.priority}</p></div><details className="relative"><summary aria-label={`Project actions for ${project.title}`} className="list-none rounded-lg p-1.5 text-slate-400 hover:bg-slate-100"><MoreHorizontal className="h-5 w-5" /></summary><div className="absolute right-0 z-10 mt-1 w-44 rounded-xl border border-slate-200 bg-white p-1 shadow-xl">{!archived && onActivate ? <button onClick={onActivate} className="flex w-full items-center gap-2 rounded-lg px-3 py-2 text-left text-sm hover:bg-slate-50"><Pin className="h-4 w-4" />Make active</button> : null}<button onClick={onArchive} className={`flex w-full items-center gap-2 rounded-lg px-3 py-2 text-left text-sm ${archived ? "text-emerald-700 hover:bg-emerald-50" : "text-rose-600 hover:bg-rose-50"}`}>{archived ? <RotateCcw className="h-4 w-4" /> : <Archive className="h-4 w-4" />}{archived ? "Restore" : "Archive"}</button></div></details></div><p className="mt-4 line-clamp-2 min-h-10 text-sm leading-5 text-slate-500">{project.description}</p><div className="mt-5 flex items-center justify-between"><Badge tone={tones[project.riskStatus]}>{project.riskStatus.replace("_", " ")}</Badge>{project.manualProgress !== null ? <Badge tone="purple">Manual override</Badge> : null}<span className="ml-auto flex items-center gap-1.5 text-xs font-medium text-slate-500"><CalendarDays className="h-3.5 w-3.5" />{format(parseISO(project.finalDeadline), "d MMM yyyy")}</span></div><div className="mt-5"><div className="mb-2 flex items-end justify-between text-sm"><span className="text-slate-500">Progress <strong className="ml-1 text-slate-900">{project.displayedProgress}%</strong></span><span className={project.progressVariance < 0 ? "font-semibold text-rose-600" : "font-semibold text-emerald-600"}>{project.progressVariance > 0 ? "+" : ""}{project.progressVariance} pts</span></div><Progress value={project.displayedProgress} expected={project.expectedProgress} /></div><Link href={`/projects/${project.id}`} className="mt-5 flex items-center justify-between border-t border-slate-100 pt-4 text-sm font-semibold text-slate-700">Open project <ArrowUpRight className="h-4 w-4 transition group-hover:-translate-y-0.5 group-hover:translate-x-0.5" /></Link></article>;
}
